### ISSUE TITLE
Fix GitHub vulnerabilities:

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/green-up-app-old#135]
```
GitHub found 14 vulnerabilities on codeforbtv/green-up-app's default branch (11 high, 3 moderate). To find out more, visit: https://github.com/codeforbtv/green-up-app/network/alerts
```

**Comment by cfrank0214** [comment]
**I've decided to focus on these three vulnerabilities.**

✗ Medium severity vulnerability found in axios
  Description: Denial of Service (DoS)
  Introduced through: expo-cli@3.0.10
  From: expo-cli@3.0.10 > @expo/xdl@56.2.1 > analytics-node@3.3.0 > axios@0.17.1
  Remediation: 
    Some paths have no direct dependency upgrade that can address this issue. Run `snyk wizard` to explore remediation options.

✗ High severity vulnerability found in plist
  Description: Regular Expression Denial of Service (ReDoS)
  Introduced through: expo-cli@3.0.10
  From: expo-cli@3.0.10 > @expo/xdl@56.2.1 > plist@2.1.0
  Fixed in: 3.0.1

✗ High severity vulnerability found in lodash
  Description: Prototype Pollution
  Introduced through: expo-cli@3.0.10
  From: expo-cli@3.0.10 > lodash@4.17.11
  From: expo-cli@3.0.10 > @expo/xdl@56.2.1 > lodash@4.17.11
  Remediation: 

Package manager:   yarn
Target file:       yarn.lock
Open source:       no
Project path:      /codeforbtv/green-up-app

Tested 1994 dependencies for known vulnerabilities, found 5 vulnerabilities, 24 vulnerable paths.
