### ISSUE TITLE
Delayed Update of Changed Team Name

### ISSUE THREAD

**Issue by nfloersch** [codeforbtv/green-up-app-old#296]
**Describe the bug**
As owner of a team I change the team name. Upon hitting "save" the GUI navigates back to the main screen, but does not show the changed team name on the team tile. Tapping the team again and going back to the team settings, I changed the team name again, to something else, and hit save. Upon going back to the main screen, it now shows the team tile labelled with the new team name from the first time I changed it. Classic async data update issue.

Sometimes it does change on the home screen after change, but takes a little while - maybe a full 60 seconds or more.

**To Reproduce**
1. Go to Home screen
2. Tap tile with name of your own team that you created and can edit
3. Tap Details to bring up the editable team information
4. Enter new name such as by adding a "1" to the end of your team name
5. Tap "Save" at top of screen
6. After being brought back to Home screen, old team name is not always shown immediately

**Expected behavior**
A change to data that is directly shown to the user should be reflected immediately after a "save."

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS:  iOS 13.3.1
 - Version XS

**Phone Emulators**
- Device: iPhone
 - OS: iOS 11.4
 - Version: 8

**Comment by doub1ejack** [comment]
A few thoughts:

1. @johnneed, I'm curious about this behavior given that the app works offline (which I'm just realizing I haven't really tested). What is the expected offline behavior when someone creates a team?
2. I have seen a big delay in rendering new teams on the home screen.  I suspect these are related issues - I'm guessing that the app doesn't update until after a round trip pushing info to firebase and retrieving it again. 
2. Since performance issues seem to be a reason for rejecting apps, and the teams are a primary function of the app, I added the `high priority` flag to this issue.
