### ISSUE TITLE
Unable to click on Trash Disposal on Android

### ISSUE THREAD

**Issue by kristylynn1984** [codeforbtv/green-up-app-old#305]
**Describe the bug**
When clicking "Trash Disposal" the 50th Anniversary logo flashes twice then reverts back to main screen.

**To Reproduce**
1. Log into app
2. Click on Trash Disposal onscreen
3. 50th Anniversary Logo flashes twice
4. Screen reverts back to main screen

**Expected behavior**
I believe this should have led to another screen where I could log trash being picked up and disposed of.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android / Samsung Experience
 - Version: 8.8.0 / 9.0

**Comment by nfloersch** [comment]
@doub1ejack @kmeyersvt  - this was found during our Hack Night time last night. Not sure if the stuff John pushed since then fixes it, but since this is Android, getting some verification would be good. @kristylynn1984 noted that the issue did not happen on the v3.25.20 version, but did happen in v2020-03-31 or whatever the newer version was titled.

**Comment by nfloersch** [comment]
Closing this as a newer version of the ticket has been created.
