### ISSUE TITLE
Unable to drop pin in Trash Disposal Screen

### ISSUE THREAD

**Issue by kristylynn1984** [codeforbtv/green-up-app-old#333]
**Describe the bug**
No response when trying to drop a pin on the map in the Bag Tagger screen.

**To Reproduce**
1. Go to 'Trash Disposal'
2. Click on 'Bag Tagger'
3. Attempt to drop pin by tapping the map
4. Nothing happens

**Expected behavior**
A pin would drop on the map.

**App Version (found on "Menu" screen):** 3.0.14

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0.0

**Comment by nfloersch** [comment]
This is somewhere between a bug and functioning as written I think. From what I have seen of the original code I've been working on, there are two buttons in towns with roadside pickup. These buttons, above the map, are either to drop a bag "here" (presumably meaning wherever the phone GPS shows you are), or to note you will bring the bag to a drop-off location of which it provides a list.

Tapping the map before you choose an option seems to have no effect. Once you choose an option, however, a pin does show on the map.

So the question is if the map is supposed to be an interface to define where a bag was dropped, or if it is only meant to show where the bag drop is on a map (not super useful but could have been the original plan?)

I'm leaving it open, but I'm taking MUSTFIX off of it for now because this is not preventing a bag drop - it is just a strange UX at best.

**Comment by nfloersch** [comment]
As an update, the reason nothing happens is because there is no map click function/handler on the Trash Drop Form. I've been working on creating one, but the pins I create refuse to render so... its ongoing.
