### ISSUE TITLE
Unable to exit help menu using the X in Trash Disposal

### ISSUE THREAD

**Issue by kristylynn1984** [codeforbtv/green-up-app-old#334]
**Describe the bug**
In the Town Info screen, clicking the ? brings up a message and nothing happens when clicking the X to close it. The phone's back button needs to be used instead to get the message to go away.

**To Reproduce**
1. Go to 'Trash Disposal'
2. Click/stay on 'Town Info'
3. Click '?.'
4. Try clicking the 'X' to close

**Expected behavior**
Clicking X would close the message

**Screenshots**
![Screenshot_20200416-164613_Expo](https://user-images.githubusercontent.com/62626323/79506878-bb5ed400-8004-11ea-903a-6c937c8cc9a2.jpg)

**App Version (found on "Menu" screen):** 3.0.14

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0.0

**Comment by nfloersch** [comment]
This may suffer from the same issue we saw with the map's toggle switch controls. The basis of the issue was that there is an attempt to treat the content as a modal, and Android does not do modals the same way as iOS... so the easiest solution ended up ditching the modal concept and just using an additional screen in the screen stack to hold the content.
